[2021-10-18 17:12:51,416][INFO][4525964800][main.py:88]SSRSpeed 1.01, Web Api Version 0.5.2
[2021-10-18 17:12:51,418][INFO][4525964800][requirements_check.py:73]Checking libsodium.
[2021-10-18 17:12:55,319][INFO][4525964800][requirements_check.py:57]Checking ./clients/v2ray-core/v2ctl
[2021-10-18 17:12:55,320][INFO][4525964800][requirements_check.py:57]Checking ./clients/v2ray-core/v2ray
[2021-10-18 17:12:55,322][INFO][4525964800][requirements_check.py:123]Shadowsocks-libev found /usr/local/bin/ss-local
[2021-10-18 17:12:55,322][INFO][4525964800][requirements_check.py:120]Obfs-Local found /usr/local/bin/obfs-local
[2021-10-18 17:12:55,323][INFO][4525964800][config_parser.py:176]Reading https://fast.losadhwselfff2332dasd.xyz/link/UHFeqi6SwVAesyOi?clash=2
[2021-10-18 17:12:56,894][INFO][4525964800][config_parser.py:220]Base64 decode failed.
[2021-10-18 17:12:57,678][INFO][4525964800][config_parser.py:152]netflix - 新加坡 Legacy Magic IEPL 中继 C01 Netflix
[2021-10-18 17:12:57,678][INFO][4525964800][config_parser.py:152]netflix - 新加坡 Legacy Magic IEPL 中继 C02 Netflix
[2021-10-18 17:12:57,679][INFO][4525964800][config_parser.py:152]netflix - 新加坡 Legacy Magic IEPL 中继 C03 Netflix
[2021-10-18 17:12:57,679][INFO][4525964800][config_parser.py:152]netflix - 新加坡 Legacy Magic IEPL 中继 C04 Netflix
[2021-10-18 17:12:57,679][INFO][4525964800][config_parser.py:152]netflix - 新加坡 Legacy Magic IEPL 中继 C05 Netflix
[2021-10-18 17:12:57,679][INFO][4525964800][config_parser.py:152]netflix - 新加坡 Magic IEPL 中继 C01 Netflix
[2021-10-18 17:12:57,680][INFO][4525964800][config_parser.py:152]netflix - 新加坡 Magic IEPL 中继 C02 Netflix
[2021-10-18 17:12:57,680][INFO][4525964800][config_parser.py:152]netflix - 新加坡 Magic IEPL 中继 C03 Netflix
[2021-10-18 17:12:57,680][INFO][4525964800][config_parser.py:152]netflix - 新加坡 Magic IEPL 中继 C04 Netflix
[2021-10-18 17:12:57,681][INFO][4525964800][config_parser.py:152]netflix - 新加坡 Magic IEPL 中继 C05 Netflix
[2021-10-18 17:12:57,681][INFO][4525964800][config_parser.py:152]netflix - 新加坡高级 IEPL 中继 C01 Netflix
[2021-10-18 17:12:57,681][INFO][4525964800][config_parser.py:152]netflix - 新加坡高级 IEPL 中继 C02 Netflix
[2021-10-18 17:12:57,682][INFO][4525964800][config_parser.py:152]netflix - 新加坡高级 IEPL 中继 C03 Netflix
[2021-10-18 17:12:57,682][INFO][4525964800][ssrspeed_core.py:165]13 node(s) will be test.
[2021-10-18 17:12:57,683][INFO][4525964800][speed_test.py:421]Test mode : speed and tcp ping.Test method : FAST.
[2021-10-18 17:12:57,684][INFO][4525964800][speed_test.py:242]Starting test netflix - 新加坡 Legacy Magic IEPL 中继 C01 Netflix [1/13]
[2021-10-18 17:12:57,690][INFO][4525964800][client_shadowsocks.py:36]Starting Shadowsocks-libev with server sgp01.cathayroute.com:33400
[2021-10-18 17:12:58,698][INFO][4525964800][speed_test.py:276]Client started.
[2021-10-18 17:12:59,704][INFO][4525964800][geo_ip.py:46]Translating sgp01.cathayroute.com to ipv4.
[2021-10-18 17:12:59,706][INFO][4525964800][geo_ip.py:63]Starting Geo IP.
[2021-10-18 17:13:00,600][INFO][4525964800][speed_test.py:111]Node inbound IP : 162.14.13.189, Geo : Hong Kong Unknown City, Tencent cloud computing
[2021-10-18 17:13:00,600][INFO][4525964800][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 17:13:02,466][INFO][4525964800][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 17:13:04,570][INFO][4525964800][geo_ip.py:63]Starting Geo IP.
[2021-10-18 17:13:05,541][INFO][4525964800][speed_test.py:127]Node outbound IP : 50.7.253.98, Geo : Singapore Singapore, Fdcservers
[2021-10-18 17:13:05,541][INFO][4525964800][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 17:13:08,530][INFO][4525964800][speed_test.py:153]Netflix IP : 39.109.245.22
[2021-10-18 17:13:11,221][INFO][4525964800][speed_test.py:173]Netflix test result: DNS解锁.
[2021-10-18 17:13:11,221][INFO][4525964800][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 17:13:12,790][INFO][4525964800][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 17:13:12,791][WARNING][4525964800][speed_test.py:374]Re-testing node.
[2021-10-18 17:13:12,791][INFO][4525964800][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 17:13:12,791][INFO][4525964800][speed_test.py:386][netflix] - [新加坡 Legacy Magic IEPL 中继 C01 Netflix] - Loss: [0.00%] - TCP Ping: [86.00] - Google Loss: [0.00%] - Google Ping: [209.00] - AvgStSpeed: [0.00MB/s] - AvgMtSpeed: [0.00MB/s] - NAT Type: Full-cone NAT - Internal End: 10.10.20.57:54320 - Public End: 50.7.253.98:45502
[2021-10-18 17:13:13,793][INFO][4525964800][speed_test.py:242]Starting test netflix - 新加坡 Legacy Magic IEPL 中继 C02 Netflix [2/13]
[2021-10-18 17:13:13,801][INFO][4525964800][client_shadowsocks.py:36]Starting Shadowsocks-libev with server sgp02.cathayroute.com:33400
[2021-10-18 17:13:14,808][INFO][4525964800][speed_test.py:276]Client started.
[2021-10-18 17:13:15,814][INFO][4525964800][geo_ip.py:46]Translating sgp02.cathayroute.com to ipv4.
[2021-10-18 17:13:15,815][INFO][4525964800][geo_ip.py:63]Starting Geo IP.
[2021-10-18 17:13:16,888][INFO][4525964800][speed_test.py:111]Node inbound IP : 162.14.13.189, Geo : Hong Kong Unknown City, Tencent cloud computing
[2021-10-18 17:13:16,888][INFO][4525964800][speed_test_methods.py:72]Testing latency to server.
[2021-10-18 17:13:18,849][INFO][4525964800][speed_test_methods.py:68]Testing latency to google.
[2021-10-18 17:13:21,672][INFO][4525964800][geo_ip.py:63]Starting Geo IP.
[2021-10-18 17:13:22,634][INFO][4525964800][speed_test.py:127]Node outbound IP : 50.7.253.98, Geo : Singapore Singapore, Fdcservers
[2021-10-18 17:13:22,634][INFO][4525964800][speed_test.py:135]Performing netflix test LOCAL_PORT: 1087.
[2021-10-18 17:13:25,582][INFO][4525964800][speed_test.py:153]Netflix IP : 39.109.245.22
[2021-10-18 17:13:28,472][INFO][4525964800][speed_test.py:173]Netflix test result: DNS解锁.
[2021-10-18 17:13:28,473][INFO][4525964800][speed_test.py:218]Performing UDP NAT Type Test
[2021-10-18 17:13:29,935][INFO][4525964800][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 17:13:29,936][WARNING][4525964800][speed_test.py:374]Re-testing node.
[2021-10-18 17:13:29,936][INFO][4525964800][speed_test_methods.py:44]Starting speed test with FAST
[2021-10-18 17:13:29,936][INFO][4525964800][speed_test.py:386][netflix] - [新加坡 Legacy Magic IEPL 中继 C02 Netflix] - Loss: [0.00%] - TCP Ping: [95.00] - Google Loss: [0.00%] - Google Ping: [281.00] - AvgStSpeed: [0.00MB/s] - AvgMtSpeed: [0.00MB/s] - NAT Type: Full-cone NAT - Internal End: 10.10.20.57:54320 - Public End: 50.7.253.98:42974
[2021-10-18 17:13:30,939][INFO][4525964800][speed_test.py:242]Starting test netflix - 新加坡 Legacy Magic IEPL 中继 C03 Netflix [3/13]
[2021-10-18 17:13:30,950][INFO][4525964800][client_shadowsocks.py:36]Starting Shadowsocks-libev with server sgp03.cathayroute.com:33400
[2021-10-18 17:13:31,958][INFO][4525964800][speed_test.py:276]Client started.
[2021-10-18 17:13:32,964][INFO][4525964800][geo_ip.py:46]Translating sgp03.cathayroute.com to ipv4.
[2021-10-18 17:13:32,965][INFO][4525964800][geo_ip.py:63]Starting Geo IP.
[2021-10-18 17:13:32,994][ERROR][4525964800][geo_ip.py:76]Geo IP Failed.
Traceback (most recent call last):
  File "/Users/chinnsenn/Developments.localized/PythonProjects/SSRSpeedN-Mod/ssrspeed/utils/geo_ip.py", line 66, in IPLoc
    rep = requests.get("https://api.ip.sb/geoip/{}".format(ip),proxies = {
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/chinnsenn/.pyenv/versions/3.9.5/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
KeyboardInterrupt
[2021-10-18 17:13:33,003][INFO][4525964800][speed_test.py:111]Node inbound IP : 162.14.13.189, Geo : N/A Unknown City, N/A
[2021-10-18 17:13:33,004][INFO][4525964800][speed_test_methods.py:72]Testing latency to server.
